"use client";
import { NavBar } from "@/components/NavBar";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white">
      <NavBar />
      <div className="max-w-4xl mx-auto px-4 py-10">
        <div className="text-center mb-10">
          <h1 className="text-4xl font-bold text-gray-900 mb-3">Terms of Service</h1>
          <p className="text-gray-600">Last updated: November 2025</p>
        </div>

        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Agreement to Terms</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700">
                By accessing and using the Mental Stress Detection application ("the Service"), you accept 
                and agree to be bound by the terms and provision of this agreement. If you do not agree to 
                abide by the above, please do not use this service.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Use License</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700 mb-3">
                Permission is granted to temporarily use the Mental Stress Detection service for personal, 
                non-commercial use only. This is the grant of a license, not a transfer of title, and under 
                this license you may not:
              </p>
              <ul className="space-y-2 list-disc list-inside text-gray-700">
                <li>Modify or copy the materials</li>
                <li>Use the materials for any commercial purpose or for any public display</li>
                <li>Attempt to reverse engineer any software contained in the application</li>
                <li>Remove any copyright or other proprietary notations from the materials</li>
                <li>Transfer the materials to another person or "mirror" the materials on any other server</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Service Description</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700">
                The Mental Stress Detection service provides AI-powered text analysis to identify potential 
                stress indicators. The service is provided "as is" and is intended for informational and 
                educational purposes only. It should not be used as a substitute for professional medical 
                advice, diagnosis, or treatment.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Medical Disclaimer</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="bg-red-50 border-l-4 border-red-500 p-4 rounded">
                <p className="text-red-800 font-semibold mb-2">Important Medical Disclaimer</p>
                <p className="text-red-700 text-sm">
                  The Mental Stress Detection service is not a medical device and does not provide medical 
                  diagnosis or treatment. The predictions generated by this service are for informational 
                  purposes only and should not be considered as professional medical advice. Always seek the 
                  advice of qualified health providers with any questions you may have regarding a medical condition.
                </p>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>User Responsibilities</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700 mb-3">You agree to:</p>
              <ul className="space-y-2 list-disc list-inside text-gray-700">
                <li>Use the service only for lawful purposes</li>
                <li>Not use the service to transmit harmful, offensive, or illegal content</li>
                <li>Not attempt to gain unauthorized access to the service or its systems</li>
                <li>Not interfere with or disrupt the service or servers</li>
                <li>Respect the intellectual property rights of the service</li>
                <li>Understand that predictions are not medical diagnoses</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Limitation of Liability</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700">
                In no event shall the Mental Stress Detection application or its operators be liable for any 
                damages (including, without limitation, damages for loss of data or profit, or due to business 
                interruption) arising out of the use or inability to use the materials on the application, even 
                if the application or an authorized representative has been notified orally or in writing of the 
                possibility of such damage.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Accuracy of Materials</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700">
                The materials appearing on the Mental Stress Detection application could include technical, 
                typographical, or photographic errors. We do not warrant that any of the materials on its 
                website are accurate, complete, or current. We may make changes to the materials contained 
                on its website at any time without notice.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Service Availability</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700">
                We reserve the right to modify or discontinue the service at any time without prior notice. 
                We do not guarantee that the service will be available at all times or that it will be free 
                from errors or interruptions. We are not liable for any loss or damage resulting from service 
                unavailability.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Intellectual Property</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700">
                All content, features, and functionality of the Mental Stress Detection application, including 
                but not limited to text, graphics, logos, and software, are the property of the application 
                operators and are protected by international copyright, trademark, and other intellectual 
                property laws.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Modifications</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700">
                We reserve the right to revise these terms of service at any time without notice. By using 
                this service, you are agreeing to be bound by the then current version of these terms of service.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Governing Law</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700">
                These terms and conditions are governed by and construed in accordance with applicable laws. 
                Any disputes relating to these terms shall be subject to the exclusive jurisdiction of the 
                courts in the applicable jurisdiction.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Contact Information</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-700">
                If you have any questions about these Terms of Service, please contact us through our 
                <a href="/contact" className="text-purple-600 hover:underline ml-1">contact page</a>.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}

